spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/tracing-issue"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1
    enabled: true
  otlp:
    metrics:
      export:
        enabled: true
        url: http://localhost:4318/v1/metrics
    tracing:
      endpoint: http://localhost:4318/v1/traces



