apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    version: 1
    uid: tempo
    editable: true
    url: http://monitoring-tempo:3100
    isDefault: false
    basicAuth: false
    apiVersion: 1
    jsonData: {}

  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    version: 1
    uid: prometheus
    editable: true
    url: http://monitoring-prometheus:9090
    isDefault: false
    basicAuth: false
    jsonData:
      httpMethod: "POST"
      manageAlerts: false
